### ISSUE TITLE
balance spawn process

### ISSUE THREAD

**Issue by JonathanSafer** [JonathanSafer/screeps#129]
spawn queue creeps shouldn't come last or first, rather they should be spawned as if they were under quota

**Comment by JonathanSafer** [comment]
maybe take the role of the first creep in queue and drop the associated role count to 0 for that tick?

**Comment by jordansafer** [comment]
I don’t think i understand. what is the role count?

**Comment by JonathanSafer** [comment]
The role count is the census that is used to determine if we have enough of each role

**Comment by jordansafer** [comment]
i think we should put things in the spawn queue based on the census. so if we don’t have enough of a certain role we add it to the spawn queue. we can add logic to the spawn queue later to prioritize certain roles

**Comment by JonathanSafer** [comment]
SpawnQueue now gets sorted by spawn priority
