### ISSUE TITLE
Creeps not moving (issue with newMove?) in screeps world

### ISSUE THREAD

**Issue by mdnowicky** [JonathanSafer/screeps#176]
The AI doesn't work in screeps world for me anymore. Errors out with "pathing failure at-". Works on my private server but something with the motion module is broken in screeps world now.

**Comment by JonathanSafer** [comment]
@mdnowicky are you in a Novice zone or Respawn zone by any chance? The bot has some safeguards in place to prevent terrorizing noobs. If you spawn in a normal grey room it should work just fine.
