### ISSUE TITLE
Newbie help

### ISSUE THREAD

**Issue by pacomms** [JonathanSafer/screeps#179]
How do i use this on my server ? when i load the code into my folder from a git download it just scrolls cannot find module 

Error: Unknown module 'lib/utils'
    at Object.requireFn (<runtime>:20840:23)
    at main:1:45
    at main:181:3
    at Object.exports.evalCode (<runtime>:15370:76)
    at Object.requireFn (<runtime>:20858:28)
    at Object.exports.run (<runtime>:20801:60)

Be kind total newbie here, just wanted to see your code to give me ideas :-)

**Comment by Kyo0x** [comment]
Yeah, can't seem to figure out why myself either, maybe Jonathan knows :)

**Comment by pacomms** [comment]
maybe its a tad odd, just wont find the modules at all, Jonathan help :-)

**Comment by jordansafer** [comment]
You need to use the rollup command to combine everything into 1 file. The command is `npm run roll`, which will generate a file at dist/main.js-
