### ISSUE TITLE
Circular Dependencies

### ISSUE THREAD

**Issue by pacomms** [JonathanSafer/screeps#180]
When you create the js using rollup it gives errors about circular dependencies ? this causes the code to throw multiple errors when running and crashes the script

(!) Circular dependencies
src/roles/upgrader.js -> src/roles/builder.js -> src/roles/upgrader.js
src/roles/harasser.js -> src/managers/military.js -> src/roles/quad.js -> src/roles/harasser.js
src/roles/harasser.js -> src/managers/military.js -> src/roles/quad.js -> /npm/screeps/src/roles/harasser.js?commonjs-proxy -> src/roles/harasser.js
src/roles/upgrader.js -> src/roles/builder.js -> /npm/screeps/src/roles/upgrader.js?commonjs-proxy -> src/roles/upgrader.js

**Comment by jordansafer** [comment]
Hi @pacomms  yes, it does give warnings, but the output is generated successfully. The output is stored in dist/main.js-
