### ISSUE TITLE
cannot read property 'room' of undefined

### ISSUE THREAD

**Issue by couchcactus** [JonathanSafer/screeps#207]
mysterious error message appearing that does nothing except prevent using console commands

**Comment by JonathanSafer** [comment]
Do you have a line number for that error?

**Comment by couchcactus** [comment]
yes, it was 11049, the code for homeless creeps

**Comment by couchcactus** [comment]
also i respawned because of this error, but the runner and remote miner seem to do nothing. they just spawned and the runner isn't pulling the miner along

**Comment by couchcactus** [comment]
![image](https://github.com/JonathanSafer/screeps/assets/167353923/289fe5ea-05f0-496b-a4b0-50629262605b)

**Comment by JonathanSafer** [comment]
Ah it's because you're in a novice zone. Try respawning in a normal area and let me know if the problem persists

**Comment by couchcactus** [comment]
oh ok lol thanks

**Comment by couchcactus** [comment]
but anyways for the error message, it happened when a quad was attacking a room, and this is the code line error:
            _.forEach(localCreeps["homeless"], (creep) => {

**Comment by JonathanSafer** [comment]
I'll look into this more later today. In the future if you notice that a creep is causing the whole bot to crash, you can "resolve" the issue by suiciding that creep. Of course ideally we'll get to the point where creeps are never able to crash the whole bot :).

**Comment by couchcactus** [comment]
yeah, it happened when the quad was attacked and lost 2 members. They sat outside the room doing nothing and then the error appeared. I suicided them but nothing happened, could be the memory but it doesn't mention that in the error

**Comment by JonathanSafer** [comment]
This makes me think that the error wasn't related to the quad. Do you have a link to the history for that attack by any chance? When I take a look at the code later that might be useful for me to get some context.

**Comment by couchcactus** [comment]
yeah, i don't think i do, i will check though

**Comment by couchcactus** [comment]
ok so shard 3 W31N24 Tick 58097879 is when the error hit, check out what it did to the colony

**Comment by couchcactus** [comment]
and shard 3 W34N24 tick 58097679

**Comment by couchcactus** [comment]
have you got a discord? i think discussing this will be better there
