### ISSUE TITLE
Build links ASAP

### ISSUE THREAD

**Issue by jordansafer** [JonathanSafer/screeps#77]
Current roomplanner code waits until rcl7/8 to build links outside of the core city limits, but link planner should run based on the number of links available (2 available at rcl5 => 1 miner should use a link)

**Comment by JonathanSafer** [comment]
We now build links at RCL 6. Having one miner use a link would save 1 energy/tick from decay, but would require miners to have carry parts, as well as a RCL 5 ferry.
