### ISSUE TITLE
Pre storage body types

### ISSUE THREAD

**Issue by JonathanSafer** [JonathanSafer/screeps#81]
before the storage is built, many of the current body types and spawning methods contribute to stalling the room. For example, transporters are excessively large, and miners have more works than they need while also mining out their sources faster than needed.

**Comment by jordansafer** [comment]
not major bc it's not a big feature (ie factories, quads, global vision usage, automated empire expansion)

**Comment by jordansafer** [comment]
+1 another city broken bc this

**Comment by jordansafer** [comment]
mitigated by enabling emergency mode
